name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Hugging Face Hub CLI
        run: pip install huggingface_hub
      - name: Push to hub
        run: huggingface-cli upload Divya499/Credit-card-fraud_detection . . --repo-type space --exclude ".git/*" --exclude "__pycache__/*" --exclude ".github/*" --token ${{ secrets.HF_TOKEN }}

